import { spawn, execFile, type ChildProcessWithoutNullStreams } from "node:child_process";
import { randomUUID } from "node:crypto";
import type { Logger } from "pino";
import { TwinnyError, toErrorMessage } from "../errors.js";
import type { CodexTurnInput } from "../codex/turn.js";
import { logger as defaultLogger } from "../observability/logs.js";
import type { CodexAgentMessage, CodexThreadTokenUsageUpdate, CodexTurnResult, ProfileName } from "../types.js";
import {
  addClaudeUsage,
  buildClaudeUserMessage,
  claudeUsageToTokenUsageUpdate,
  claudeUsageTotalTokens,
  emptyClaudeUsage,
  parseClaudeStreamLine,
  type ClaudeUsage
} from "./claude-stream.js";

export interface ClaudeThreadStartParams {
  profile: ProfileName;
  cwd: string;
  approvalPolicy: "never";
  developerInstructions?: string;
  model?: string;
  effort?: string;
}

export interface ClaudeThreadResumeParams {
  profile: ProfileName;
  threadId: string;
  cwd: string;
  approvalPolicy: "never";
}

export interface ClaudeThreadForkParams {
  profile: ProfileName;
  threadId: string;
  cwd: string;
  approvalPolicy: "never";
  ephemeral?: boolean;
  developerInstructions?: string;
  model?: string;
  effort?: string;
}

export interface ClaudeTurnStartParams {
  profile: ProfileName;
  threadId: string;
  input: CodexTurnInput;
  currentThreadName?: string;
  cwd: string;
  approvalPolicy: "never";
  mode?: string;
  model?: string;
  effort?: string;
  onTurnStarted?: (turnId: string) => Promise<void> | void;
  onAgentMessage?: (message: CodexAgentMessage) => Promise<void> | void;
  onTokenUsage?: (usage: CodexThreadTokenUsageUpdate) => Promise<void> | void;
}

export interface ClaudeHarnessOptions {
  binary: string;
  logger?: Logger;
  claudeConfigDirFor?: (profile: ProfileName) => string | undefined;
  readThreadTokenSeed?: (threadId: string) => ClaudeUsage | undefined;
  spawnFn?: typeof spawn;
  env?: NodeJS.ProcessEnv;
}

interface ClaudeThreadState {
  /** True once a session with this id exists on disk (a turn completed). */
  created: boolean;
  /** Set when this logical thread is a fork that has not run its first turn yet. */
  forkOf?: string;
  developerInstructions?: string;
  /** Pending context blocks injected via injectThreadItems (side boundary emulation). */
  pendingPreambles: string[];
  /** Cumulative thread token usage as reported to the manager. */
  cumulativeUsage: ClaudeUsage;
  usageSeeded: boolean;
}

interface ActiveClaudeTurn {
  turnId: string;
  child: ChildProcessWithoutNullStreams;
  inputsSent: number;
  resultsSeen: number;
  interruptRequested: boolean;
  stdinClosed: boolean;
}

const SESSION_NOT_FOUND_PATTERNS = [/no conversation found/i, /session not found/i, /no session found/i];
const SESSION_ALREADY_EXISTS_PATTERNS = [/already in use/i, /already exists/i];

export function isClaudeSessionNotFoundError(output: string): boolean {
  return SESSION_NOT_FOUND_PATTERNS.some((pattern) => pattern.test(output));
}

export function isClaudeSessionAlreadyExistsError(output: string): boolean {
  return SESSION_ALREADY_EXISTS_PATTERNS.some((pattern) => pattern.test(output));
}

export function codexTurnInputToText(input: CodexTurnInput): string {
  if (typeof input === "string") {
    return input;
  }
  const parts: string[] = [];
  for (const item of input) {
    if (item.type === "text") {
      parts.push(item.text);
    } else if (item.type === "localImage") {
      parts.push(`[本地图片，请用文件工具读取] ${item.path}`);
    }
  }
  return parts.join("\n");
}

/**
 * Claude Code harness: adapts the Claude Code CLI (`claude -p` with
 * stream-json input/output) to the Codex bridge contract used by the
 * conversation manager.
 *
 * Thread mapping: a Twinny "thread" is a Claude Code session. Thread ids are
 * UUIDs generated by this bridge and forced onto the CLI via `--session-id`,
 * so sessions survive daemon restarts and `--resume <threadId>` works without
 * an alias table. Forks use `--resume <source> --fork-session --session-id
 * <newId>` on their first turn.
 *
 * Turn mapping: each Twinny turn runs one CLI process. Steering writes an
 * extra stream-json user message to the running process; Claude Code handles
 * it as the immediately-following prompt in the same session, and the bridge
 * keeps the Twinny turn open until every submitted prompt has produced a
 * result.
 */
export class ClaudeCodeHarness {
  private readonly log: Logger;
  private readonly threads = new Map<string, ClaudeThreadState>();
  private readonly activeTurns = new Map<string, ActiveClaudeTurn>();
  private readonly spawnFn: typeof spawn;
  private versionPromise?: Promise<string>;

  constructor(private readonly options: ClaudeHarnessOptions) {
    this.log = options.logger ?? defaultLogger;
    this.spawnFn = options.spawnFn ?? spawn;
  }

  async startThread(params: ClaudeThreadStartParams): Promise<{ threadId: string }> {
    const threadId = randomUUID();
    this.threads.set(threadId, {
      created: false,
      ...(params.developerInstructions ? { developerInstructions: params.developerInstructions } : {}),
      pendingPreambles: [],
      cumulativeUsage: emptyClaudeUsage(),
      usageSeeded: true
    });
    this.log.debug({ threadId, profile: params.profile }, "claude harness thread allocated");
    return { threadId };
  }

  async resumeThread(params: ClaudeThreadResumeParams): Promise<{ threadId: string }> {
    const state = this.getOrCreateThreadState(params.threadId);
    state.created = true;
    return { threadId: params.threadId };
  }

  async forkThread(params: ClaudeThreadForkParams): Promise<{ threadId: string; cwd?: string; model?: string; effort?: string }> {
    const source = this.getOrCreateThreadState(params.threadId);
    source.created = true;
    const threadId = randomUUID();
    this.threads.set(threadId, {
      created: false,
      forkOf: params.threadId,
      ...(params.developerInstructions ? { developerInstructions: params.developerInstructions } : {}),
      pendingPreambles: [],
      cumulativeUsage: emptyClaudeUsage(),
      usageSeeded: true
    });
    return {
      threadId,
      cwd: params.cwd,
      ...(params.model ? { model: params.model } : {}),
      ...(params.effort ? { effort: params.effort } : {})
    };
  }

  /**
   * Codex `thread/inject_items` emulation: Claude Code has no API to insert
   * synthetic history items, so injected text is buffered and prepended to
   * the next prompt of this thread inside a <context> block.
   */
  async injectThreadItems(params: { profile: ProfileName; threadId: string; items: unknown[] }): Promise<void> {
    const state = this.getOrCreateThreadState(params.threadId);
    for (const item of params.items) {
      const text = extractInjectedItemText(item);
      if (text) {
        state.pendingPreambles.push(text);
      }
    }
  }

  async unsubscribeThread(_params: { profile: ProfileName; threadId: string }): Promise<void> {
    // Claude Code has no notification subscription; nothing to release.
  }

  async startTurn(params: ClaudeTurnStartParams): Promise<CodexTurnResult> {
    if (this.activeTurns.has(params.threadId)) {
      throw new TwinnyError(
        `Claude Code thread ${params.threadId} already has an active turn`,
        "CLAUDE_TURN_ALREADY_ACTIVE"
      );
    }
    const state = this.getOrCreateThreadState(params.threadId);
    this.seedThreadUsage(params.threadId, state);

    const preambles = state.pendingPreambles.splice(0);
    let inputText = codexTurnInputToText(params.input);
    if (preambles.length > 0) {
      inputText = `<context>\n${preambles.join("\n\n")}\n</context>\n\n${inputText}`;
    }

    try {
      return await this.runTurnProcess(params, state, inputText, this.sessionArgs(params.threadId, state));
    } catch (error) {
      if (error instanceof ClaudeSessionStateError) {
        // Self-heal stale in-memory session state (e.g. after restarts):
        // retry once with the opposite session flag.
        const retryArgs = error.kind === "not_found"
          ? ["--session-id", params.threadId]
          : ["--resume", params.threadId];
        this.log.warn(
          { threadId: params.threadId, kind: error.kind },
          "claude harness retrying turn with corrected session flags"
        );
        return await this.runTurnProcess(params, state, inputText, retryArgs);
      }
      throw error;
    }
  }

  async steerTurn(params: {
    profile: ProfileName;
    threadId: string;
    turnId: string;
    input: CodexTurnInput;
    cwd: string;
    approvalPolicy: "never";
  }): Promise<void> {
    const active = this.activeTurns.get(params.threadId);
    if (!active || active.turnId !== params.turnId) {
      throw new TwinnyError("No active Claude Code turn to steer", "CLAUDE_NO_ACTIVE_TURN");
    }
    if (active.stdinClosed || !active.child.stdin.writable) {
      throw new TwinnyError("Claude Code turn input is already closed", "CLAUDE_TURN_INPUT_CLOSED");
    }
    const payload = buildClaudeUserMessage(codexTurnInputToText(params.input));
    active.inputsSent += 1;
    try {
      await new Promise<void>((resolve, reject) => {
        active.child.stdin.write(payload + "\n", (error) => (error ? reject(error) : resolve()));
      });
    } catch (error) {
      active.inputsSent -= 1;
      throw error;
    }
  }

  async interruptTurn(params: { profile: ProfileName; threadId: string; turnId: string }): Promise<void> {
    const active = this.activeTurns.get(params.threadId);
    if (!active || active.turnId !== params.turnId) {
      throw new TwinnyError("no active turn to interrupt", "CLAUDE_NO_ACTIVE_TURN");
    }
    active.interruptRequested = true;
    active.child.kill("SIGINT");
    setTimeout(() => {
      if (!active.child.killed || active.child.exitCode === null) {
        active.child.kill("SIGKILL");
      }
    }, 5_000).unref?.();
  }

  /**
   * Codex `thread/compact/start` emulation: runs Claude Code's built-in
   * `/compact` command as a print-mode prompt on the session.
   */
  async compactThread(params: {
    profile: ProfileName;
    threadId: string;
    cwd: string;
    approvalPolicy: "never";
    onTurnStarted?: (turnId: string) => Promise<void> | void;
    onTokenUsage?: (usage: CodexThreadTokenUsageUpdate) => Promise<void> | void;
  }): Promise<CodexTurnResult> {
    return await this.startTurn({
      profile: params.profile,
      threadId: params.threadId,
      input: "/compact",
      cwd: params.cwd,
      approvalPolicy: "never",
      ...(params.onTurnStarted ? { onTurnStarted: params.onTurnStarted } : {}),
      ...(params.onTokenUsage ? { onTokenUsage: params.onTokenUsage } : {})
    });
  }

  async readClaudeVersion(): Promise<string> {
    this.versionPromise ??= new Promise<string>((resolve) => {
      execFile(this.options.binary, ["--version"], { timeout: 10_000 }, (error, stdout) => {
        if (error) {
          resolve("不可用");
          return;
        }
        resolve(stdout.trim() || "不可用");
      });
    });
    return this.versionPromise;
  }

  private sessionArgs(threadId: string, state: ClaudeThreadState): string[] {
    if (state.forkOf && !state.created) {
      return ["--resume", state.forkOf, "--fork-session", "--session-id", threadId];
    }
    if (state.created) {
      return ["--resume", threadId];
    }
    return ["--session-id", threadId];
  }

  private seedThreadUsage(threadId: string, state: ClaudeThreadState): void {
    if (state.usageSeeded) {
      return;
    }
    state.usageSeeded = true;
    const seed = this.options.readThreadTokenSeed?.(threadId);
    if (seed) {
      state.cumulativeUsage = seed;
    }
  }

  private async runTurnProcess(
    params: ClaudeTurnStartParams,
    state: ClaudeThreadState,
    inputText: string,
    sessionArgs: string[]
  ): Promise<CodexTurnResult> {
    const startedAt = Date.now();
    const turnId = randomUUID();
    const args = [
      "-p",
      "--input-format",
      "stream-json",
      "--output-format",
      "stream-json",
      "--verbose",
      // Codex turns run with approvalPolicy "never" + dangerFullAccess; the
      // Claude Code equivalent is bypassing permission prompts. Plan mode
      // maps onto Claude Code's read-only plan permission mode instead.
      ...(params.mode === "plan" ? ["--permission-mode", "plan"] : ["--dangerously-skip-permissions"]),
      ...sessionArgs
    ];
    if (params.model) {
      args.push("--model", params.model);
    }
    if (params.effort) {
      args.push("--settings", JSON.stringify({ effort: params.effort }));
    }
    if (state.developerInstructions) {
      args.push("--append-system-prompt", state.developerInstructions);
    }

    const claudeConfigDir = this.options.claudeConfigDirFor?.(params.profile);
    const env: NodeJS.ProcessEnv = {
      ...(this.options.env ?? process.env),
      ...(claudeConfigDir ? { CLAUDE_CONFIG_DIR: claudeConfigDir } : {})
    };

    this.log.info(
      { threadId: params.threadId, turnId, profile: params.profile, model: params.model, effort: params.effort },
      "claude harness turn starting"
    );

    const child = this.spawnFn(this.options.binary, args, {
      cwd: params.cwd,
      env,
      stdio: ["pipe", "pipe", "pipe"]
    }) as ChildProcessWithoutNullStreams;

    const active: ActiveClaudeTurn = {
      turnId,
      child,
      inputsSent: 0,
      resultsSeen: 0,
      interruptRequested: false,
      stdinClosed: false
    };
    this.activeTurns.set(params.threadId, active);

    try {
      return await this.collectTurn(params, state, active, inputText, startedAt);
    } finally {
      if (this.activeTurns.get(params.threadId) === active) {
        this.activeTurns.delete(params.threadId);
      }
    }
  }

  private collectTurn(
    params: ClaudeTurnStartParams,
    state: ClaudeThreadState,
    active: ActiveClaudeTurn,
    inputText: string,
    startedAt: number
  ): Promise<CodexTurnResult> {
    const child = active.child;
    const threadId = params.threadId;
    const log = this.log;

    return new Promise<CodexTurnResult>((resolve, reject) => {
      let settled = false;
      let stdoutBuffer = "";
      let stderrTail = "";
      let initSeen = false;
      let turnStartedEmitted = false;
      let pendingText: { id: string; text: string } | undefined;
      let commentaryIndex = 0;
      const resultTexts: string[] = [];
      let lastAssistantUsage: ClaudeUsage | undefined;
      let contextWindow: number | undefined;
      let sawErrorResult = false;
      let callbackChain: Promise<void> = Promise.resolve();

      const settle = (fn: () => void): void => {
        if (!settled) {
          settled = true;
          fn();
        }
      };

      const chainCallback = (run: () => Promise<void> | void): void => {
        callbackChain = callbackChain.then(run).catch((error: unknown) => {
          log.warn({ error, threadId }, "claude harness turn callback failed");
        });
      };

      const emitAgentMessage = (message: CodexAgentMessage): void => {
        if (!params.onAgentMessage) {
          return;
        }
        chainCallback(() => params.onAgentMessage?.(message));
      };

      const flushPendingAsCommentary = (): void => {
        if (!pendingText) {
          return;
        }
        const message = pendingText;
        pendingText = undefined;
        emitAgentMessage({ id: message.id, text: message.text, phase: "commentary" });
      };

      const recordTokenUsage = (turnUsage: ClaudeUsage): void => {
        state.cumulativeUsage = addClaudeUsage(state.cumulativeUsage, turnUsage);
        if (!params.onTokenUsage) {
          return;
        }
        const update = claudeUsageToTokenUsageUpdate({
          threadId,
          turnId: active.turnId,
          cumulative: state.cumulativeUsage,
          lastTurn: turnUsage,
          ...(lastAssistantUsage !== undefined
            ? { contextTokens: claudeUsageTotalTokens(lastAssistantUsage) }
            : {}),
          ...(contextWindow !== undefined ? { contextWindow } : {})
        });
        chainCallback(() => params.onTokenUsage?.(update));
      };

      const finalize = (status: CodexTurnResult["status"], error?: string): void => {
        if (status !== "failed") {
          state.created = true;
          if (state.forkOf) {
            state.forkOf = undefined;
          }
        }
        const text = resultTexts.filter((entry) => entry.trim().length > 0).join("\n\n");
        settle(() => {
          void callbackChain.finally(() => {
            resolve({
              threadId,
              turnId: active.turnId,
              text,
              status,
              ...(error ? { error } : {}),
              durationMs: Date.now() - startedAt
            });
          });
        });
      };

      const fail = (error: TwinnyError): void => {
        settle(() => {
          void callbackChain.finally(() => reject(error));
        });
      };

      child.on("error", (error) => {
        fail(new TwinnyError(`Failed to spawn Claude Code CLI: ${toErrorMessage(error)}`, "CLAUDE_SPAWN_FAILED", error));
      });

      child.stderr.on("data", (chunk: Buffer) => {
        stderrTail = (stderrTail + chunk.toString("utf8")).slice(-4000);
      });

      child.stdout.on("data", (chunk: Buffer) => {
        stdoutBuffer += chunk.toString("utf8");
        let newlineIndex = stdoutBuffer.indexOf("\n");
        while (newlineIndex >= 0) {
          const line = stdoutBuffer.slice(0, newlineIndex);
          stdoutBuffer = stdoutBuffer.slice(newlineIndex + 1);
          handleLine(line);
          newlineIndex = stdoutBuffer.indexOf("\n");
        }
      });

      const handleLine = (line: string): void => {
        const event = parseClaudeStreamLine(line);
        if (!event) {
          return;
        }
        if (event.kind === "init") {
          initSeen = true;
          if (event.sessionId !== threadId && !(state.forkOf && !state.created)) {
            log.warn({ threadId, sessionId: event.sessionId }, "claude harness session id mismatch");
          }
          if (!turnStartedEmitted) {
            turnStartedEmitted = true;
            chainCallback(() => params.onTurnStarted?.(active.turnId));
          }
          return;
        }
        if (event.kind === "assistant") {
          if (event.usage) {
            lastAssistantUsage = event.usage;
          }
          if (event.text) {
            flushPendingAsCommentary();
            pendingText = {
              id: event.messageId ?? `claude:${active.turnId}:${commentaryIndex++}`,
              text: event.text
            };
            if (event.hasToolUse) {
              // More work follows in the same assistant message; this text is
              // narration, not the final answer.
              flushPendingAsCommentary();
            }
          }
          return;
        }
        if (event.kind === "result") {
          active.resultsSeen += 1;
          if (event.contextWindow !== undefined) {
            contextWindow = event.contextWindow;
          }
          if (event.usage) {
            recordTokenUsage(event.usage);
          }
          if (event.isError) {
            sawErrorResult = true;
          }
          const resultText = event.text?.trim() ?? "";
          const isLastExpectedResult = active.resultsSeen >= active.inputsSent;
          if (resultText) {
            resultTexts.push(resultText);
          }
          if (!isLastExpectedResult) {
            // A steered prompt is still pending: this result is intermediate.
            if (pendingText && resultText && pendingText.text === resultText) {
              pendingText = undefined;
            }
            flushPendingAsCommentary();
            if (resultText) {
              emitAgentMessage({
                id: `claude:${active.turnId}:result:${active.resultsSeen}`,
                text: resultText,
                phase: "commentary"
              });
            }
            return;
          }
          // Final result for this Twinny turn.
          if (pendingText && resultText && pendingText.text === resultText) {
            pendingText = undefined;
          }
          flushPendingAsCommentary();
          if (resultText && !event.isError) {
            emitAgentMessage({
              id: `claude:${active.turnId}:final`,
              text: resultText,
              phase: "final_answer"
            });
          }
          if (!active.stdinClosed) {
            active.stdinClosed = true;
            child.stdin.end();
          }
          return;
        }
      };

      child.on("close", (code, signal) => {
        if (settled) {
          return;
        }
        if (active.interruptRequested) {
          finalize("interrupted");
          return;
        }
        const combinedOutput = `${stderrTail}\n${stdoutBuffer}`;
        if (!initSeen && isClaudeSessionNotFoundError(combinedOutput)) {
          state.created = false;
          fail(new ClaudeSessionStateError("not_found", combinedOutput));
          return;
        }
        if (!initSeen && isClaudeSessionAlreadyExistsError(combinedOutput)) {
          state.created = true;
          fail(new ClaudeSessionStateError("already_exists", combinedOutput));
          return;
        }
        if (active.resultsSeen === 0) {
          fail(
            new TwinnyError(
              `Claude Code CLI exited before producing a result (code=${code ?? "null"}, signal=${signal ?? "null"}): ${stderrTail.trim().slice(-800) || "no stderr output"}`,
              "CLAUDE_TURN_FAILED"
            )
          );
          return;
        }
        if (sawErrorResult) {
          finalize("failed", stderrTail.trim().slice(-800) || "Claude Code reported an error result");
          return;
        }
        finalize("completed");
      });

      // Send the initial prompt.
      active.inputsSent = 1;
      child.stdin.write(buildClaudeUserMessage(inputText) + "\n", (error) => {
        if (error) {
          fail(new TwinnyError(`Failed to write Claude Code prompt: ${toErrorMessage(error)}`, "CLAUDE_TURN_FAILED", error));
        }
      });
    });
  }

  private getOrCreateThreadState(threadId: string): ClaudeThreadState {
    let state = this.threads.get(threadId);
    if (!state) {
      state = {
        // Unknown thread ids come from persisted records (daemon restarts):
        // assume the session exists and let the not-found retry correct us.
        created: true,
        pendingPreambles: [],
        cumulativeUsage: emptyClaudeUsage(),
        usageSeeded: false
      };
      this.threads.set(threadId, state);
    }
    return state;
  }
}

class ClaudeSessionStateError extends TwinnyError {
  constructor(
    readonly kind: "not_found" | "already_exists",
    output: string
  ) {
    super(`Claude Code session state mismatch (${kind}): ${output.trim().slice(-400)}`, "CLAUDE_SESSION_STATE");
  }
}

function extractInjectedItemText(item: unknown): string | undefined {
  if (typeof item === "string") {
    return item.trim() || undefined;
  }
  if (typeof item !== "object" || item === null) {
    return undefined;
  }
  const record = item as Record<string, unknown>;
  const content = record.content;
  if (typeof content === "string") {
    return content.trim() || undefined;
  }
  if (!Array.isArray(content)) {
    return undefined;
  }
  const parts: string[] = [];
  for (const block of content) {
    if (typeof block === "object" && block !== null) {
      const text = (block as Record<string, unknown>).text;
      if (typeof text === "string" && text.trim()) {
        parts.push(text.trim());
      }
    }
  }
  return parts.length > 0 ? parts.join("\n") : undefined;
}
